site_name: Whitespire Documentation
site_url: https://docs.whitespire.org
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.instant
    - search.suggest
    - search.highlight
plugins:
  - privacy
  - search