site_name: Whitespire Documentation
site_url: https://docs.whitespire.org
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.instant
    - search.suggest
    - search.highlight
markdown_extensions:
  - admonition
plugins:
  - privacy
  - search
extra:
  generator: false
nav:
  - Home: index.md
  - Proxmox:
    - Link Aggregation Control Protocol: proxmox/lacp.md